# This is a basic workflow to help you get started with Actions

name: first workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  firstjob:
    runs-on: self-hosted
    steps:
      - name: first-job step
        run: echo Hello Wolrd ! This is the first job
  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: second-job step
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
